baseURL = 'http://example.org/'
languageCode = 'no-NO'
title = 'My New Hugo Site'


[[module.mounts]]
source = "content"
target = "content"

[[module.mounts]]
source = "prebuild/public/sources"
target = "content/kilder"
