baseURL = '/'
defaultContentLanguage = "nb" 
title = 'Michael Helgesen'

[params.author]
name = "Michael Helgesen"

[frontmatter]
    lastmod = ["lastmod", ":fileModTime", ":default"]

[taxonomies]
  tekstemne = "tekstemner"
  laeringsemne = "laeringsemner"

[permalinks]
    tekstemner = "/emneknagger/tekstemner/:slug"
    laeringsemner = "/emneknagger/laeringsemner/:slug"

[security]
  [security.funcs]
    getenv = ['^HUGO_', '^CI$', '^USER$', '^HOME$']

[menus]
  [[menus.main]]
    name = 'Hjem'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Tekster'
    pageRef = '/tekster'
    weight = 20
  [[menus.main]]
    name = 'Journal'
    pageRef = '/journal'
    weight = 30
  [[menus.main]]
    name = 'Læringslogg'
    pageRef = '/laeringslogg'
    weight = 40
  [[menus.main]]
    name = 'Emneknagger'
    pageRef = '/emneknagger'
    weight = 50
  [[menus.main]]
    name = 'Kilder'
    pageRef = '/kilder'
    weight = 60
  [[menus.main]]
    name = "Bibliotek"
    pageRef = "/bibliotek"
    weight = 65
  [[menus.main]]
    name = 'Lenker'
    pageRef = '/lenker'
    weight = 70
  [[menus.main]]
    name = "Galleri"
    pageRef = "/galleri"
    weight = 75
  [[menus.main]]
    name = "KI"
    pageRef = "/ki"
    weight = 78
  [[menus.main]]
    name = 'Nå'
    pageRef = '/na'
    weight = 80
  [[menus.main]]
    name = 'Om'
    pageRef = '/om_mikke'
    weight = 90

[markup]
  [markup.goldmark]
